### ISSUE TITLE
[PORT REQUEST] -> 1.21.3

### ISSUE THREAD

**Issue by ExiledLizard** [DerpDerpling/NoPickupAnimation#3]
Hey, @DerpDerpling, is it ok if you write/compile a 1.21.3/1.21.x version of your **No Pickup Animation mod**?

**Comment by DerpDerpling** [comment]
sure, ill start working on it now. shouldn't be too much change

**Comment by ExiledLizard** [comment]
Awesome, thanks!

**Comment by DerpDerpling** [comment]
its out on modrinth now 
https://modrinth.com/mod/no-item-pickup-animations/version/e4lCdtqz

**Comment by ExiledLizard** [comment]
Awesome, thanks!
